import { PageData } from "./type";

export const dynamicSchema: PageData = {
  component: [
    {
      name: "CpsOrderGoodsCard",
      renderType: "RN",
      type: "viewGroup",
      ver: 16,
      bundleUrl: "",
      downgradeName: "",
      cid: 1620,
    },
    {
      name: "CommonTabsList",
      renderType: "RN",
      type: "viewGroup",
      ver: 8,
      bundleUrl: "",
      downgradeName: "",
      cid: 1622,
    },
    {
      name: "cpsCommonGoodsList",
      renderType: "RN",
      type: "viewNormal",
      ver: 11,
      bundleUrl: "",
      downgradeName: "",
      umdName: "cpsCommonGoodsList",
      cid: 1022,
    },
    {
      name: "CpsOrderStatus",
      renderType: "RN",
      type: "viewGroup",
      ver: 1,
      bundleUrl: "",
      downgradeName: "",
      cid: 1821,
    },
    {
      name: "infinity_root_node",
      renderType: "NATIVE",
      type: "viewNormal",
      ver: 1,
      cid: 0,
    },
  ],
  data: {
    CpsOrderGoodsCard_C4SZPIEnfpnxlVSJ: {
      instanceId: "CpsOrderGoodsCard_C4SZPIEnfpnxlVSJ",
      componentInstanceKey: 1458245002,
      name: "CpsOrderGoodsCard",
      cid: 1620,
      ver: 16,
      style: {
        layout: {
          padding: [16, 16, 16, 16],
          margin: [0, 0, 16, 0],
        },
      },
      engineConfig: {},
      fields: {
        orderId: 2425000123217732,
        settlementBizType: 1,
        orderStatus: {
          value: 6,
          label: "已发货",
          color: "#fe3666",
        },
        imgUrl:
          "https://u1-203.ecukwai.com/bs2/image-kwaishop-product/ITEM_IMAGE-2359894008-1b19a9017b134f8b940ad93562954f77.jpg",
        itemTitle: "订单动态化-普通招商商品",
        itemPrice: "0.10",
        createTime: 1725592127406,
        cpsOrderType: 7,
        promotionTags: [
          {
            value: 7,
            label: "快手商城推广",
            action: {
              type: "jump",
              target: "_blank",
              url: "https://docs.qingque.cn/d/home/eZQCP0zCpxFQaOBZIqRQVWwXr?identityId=1oE1lmldGhH",
            },
          },
        ],
        orderInfos: [
          "达人素材在商城场域内展示推广",
          "店铺名称: 铜锣湾扛把子自动化账号",
          "2024年09月06日 11:12:09 付款",
        ],
        orderIndicators: [
          {
            label: "佣金率",
            type: 5,
            name: "commissionRateIndicator",
            value: "48%",
            icon: false,
          },
          {
            label: "分成比例",
            type: 6,
            name: "shareRateIndicator",
            value: "90%",
            icon: true,
            action: {
              type: "modal",
              title: "分成比例",
              content: ["该订单为快手商城场域内成交，分佣规则可"],
              aLink: {
                title: "查看详情",
                url: "https://docs.qingque.cn/d/home/eZQCP0zCpxFQaOBZIqRQVWwXr?identityId=1rdoxqnN9Od",
              },
            },
          },
          {
            label: "预估收入",
            type: 7,
            name: "estimatedIncomeIndicator",
            value: "0.03",
            icon: true,
            action: {
              type: "modal",
              title: "预估收入说明",
            },
          },
        ],
      },
      track: {},
    },
    CpsOrderGoodsCard_fxQbDWQ4ZolYMdRB: {
      instanceId: "CpsOrderGoodsCard_fxQbDWQ4ZolYMdRB",
      componentInstanceKey: 1458245002,
      name: "CpsOrderGoodsCard",
      cid: 1620,
      ver: 16,
      style: {
        layout: {
          padding: [16, 0, 16, 0],
          margin: [0, 0, 16, 0],
        },
      },
      engineConfig: {},
      fields: {
        orderId: 2424900033306732,
        settlementBizType: 1,
        orderStatus: {
          value: 6,
          label: "已发货",
          color: "#fe3666",
        },
        imgUrl:
          "https://u1-203.ecukwai.com/bs2/image-kwaishop-product/ITEM_IMAGE-2359894008-1b19a9017b134f8b940ad93562954f77.jpg",
        itemTitle: "订单动态化-二级团专用商品",
        itemPrice: "0.10",
        createTime: 1725542324395,
        cpsOrderType: 2,
        promotionTags: [],
        orderInfos: [
          "店铺名称: 铜锣湾扛把子自动化账号",
          "2024年09月05日 21:18:51 付款",
        ],
        orderIndicators: [
          {
            label: "佣金率",
            type: 5,
            name: "commissionRateIndicator",
            value: "49%",
            icon: false,
          },
          {
            label: "分成比例",
            type: 6,
            name: "shareRateIndicator",
            value: "90%",
            icon: true,
            action: {
              type: "modal",
              title: "分成比例",
              btn: {
                type: "jump",
                btnType: "primary",
                title: "查看政策详情",
                url: "https://edu.kwaixiaodian.com/bbs/web/article?id=17963&layoutType=4",
              },
            },
          },
          {
            label: "预估收入",
            type: 7,
            name: "estimatedIncomeIndicator",
            value: "0.04",
            icon: true,
            action: {
              type: "modal",
              title: "预估收入说明",
            },
          },
        ],
      },
      track: {},
    },
    ComponentWithErrorBoundary: {
      instanceId: "ComponentWithErrorBoundary",
      componentInstanceKey: 1452245004001,
      name: "ComponentWithErrorBoundary",
      cid: 1022,
      ver: 11,
      style: {
        layout: {
          padding: [0, 0, 0, 0],
          margin: [0, 0, 0, 0],
        },
      },
      engineConfig: {},
      fields: {
        title: "Title ComponentWithErrorBoundary",
        value: 333444,
        name: "Static Props ComponentWithErrorBoundary",
      },
      strategy: "overwrite",
      track: {},
    },
    CompA: {
      instanceId: "CompA",
      componentInstanceKey: 1452245004002,
      name: "CompA",
      cid: "CompA",
      ver: 11,
      style: {
        layout: {
          padding: [0, 0, 0, 0],
          margin: [0, 0, 0, 0],
        },
      },
      engineConfig: {},
      fields: {
        title: "Title CompA",
        value: 111,
        name: "Static Props",
      },
      strategy: "overwrite",
      track: {},
    },
    CompB: {
      instanceId: "CompB",
      componentInstanceKey: 14522450040003,
      name: "CompB",
      cid: "CompB",
      ver: 11,
      style: {
        layout: {
          padding: [0, 0, 0, 0],
          margin: [0, 0, 0, 0],
        },
      },
      engineConfig: {},
      fields: {
        title: "Title CompB",
        value: 222,
        name: "Static Props",
      },
      strategy: "overwrite",
      track: {},
    },
    CompC: {
      instanceId: "CompC",
      componentInstanceKey: 14522450040004,
      name: "CompC",
      cid: "CompC",
      ver: 11,
      style: {
        layout: {
          padding: [0, 0, 0, 0],
          margin: [0, 0, 0, 0],
        },
      },
      engineConfig: {},
      fields: {
        title: "Title CompC",
        value: 333,
        name: "Static Props",
      },
      strategy: "overwrite",
      track: {},
    },
    CpsOrderGoodsCard_sqyeMdGxs08TUduw: {
      instanceId: "CpsOrderGoodsCard_sqyeMdGxs08TUduw",
      componentInstanceKey: 1458245002,
      name: "CpsOrderGoodsCard",
      cid: 1620,
      ver: 16,
      style: {
        layout: {
          padding: [16, 0, 16, 0],
          margin: [0, 0, 16, 0],
        },
      },
      engineConfig: {},
      fields: {
        orderId: 2423900088819093,
        settlementBizType: 1,
        orderStatus: {
          value: 5,
          label: "已失效",
          color: "#c6c6c6",
        },
        imgUrl:
          "https://u1-203.ecukwai.com/bs2/image-kwaishop-product/ITEM_IMAGE-2428997147-f13cc24c02344d7d88e6fa8a913bec1b.jpg",
        itemTitle: "团长托管回归",
        itemPrice: "30.00",
        createTime: 1724673847944,
        cpsOrderType: 2,
        promotionTags: [],
        orderInfos: ["店铺名称: 多乐乐乐乐改"],
        orderIndicators: [
          {
            label: "佣金率",
            type: 5,
            name: "commissionRateIndicator",
            value: "10%",
            icon: false,
          },
          {
            label: "分成比例",
            type: 6,
            name: "shareRateIndicator",
            value: "90%",
            icon: true,
            action: {
              type: "modal",
              title: "分成比例",
              btn: {
                type: "jump",
                btnType: "primary",
                title: "查看政策详情",
                url: "https://edu.kwaixiaodian.com/bbs/web/article?id=17963&layoutType=4",
              },
            },
          },
          {
            label: "预估收入",
            type: 7,
            name: "estimatedIncomeIndicator",
            value: "0.00",
            icon: true,
            action: {
              type: "modal",
              title: "预估收入说明",
              content: [
                "预估收入=计佣金额*佣金率*分成比例",
                "若订单包含以下情况，预估收入会做相应扣减:",
                "1.消费者使用了主播红包；",
                "2.订单有服务商/MCN机构角色参与分账。",
              ],
            },
          },
        ],
      },
      track: {},
    },
    CpsOrderGoodsCard_YRqyjI8k5moBEhoz: {
      instanceId: "CpsOrderGoodsCard_YRqyjI8k5moBEhoz",
      componentInstanceKey: 1458245002,
      name: "CpsOrderGoodsCard",
      cid: 1620,
      ver: 16,
      style: {
        layout: {
          padding: [16, 0, 16, 0],
          margin: [0, 0, 16, 0],
        },
      },
      engineConfig: {},
      fields: {
        orderId: 2423600061443732,
        settlementBizType: 1,
        orderStatus: {
          value: 5,
          label: "已失效",
          color: "#c6c6c6",
        },
        imgUrl:
          "https://u1-203.ecukwai.com/bs2/image-kwaishop-product/ITEM_IMAGE-2359894008-1b19a9017b134f8b940ad93562954f77.jpg",
        itemTitle: "达人素材-白名单专用",
        itemPrice: "0.10",
        createTime: 1724384697949,
        cpsOrderType: 2,
        promotionTags: [],
        orderInfos: ["店铺名称: 铜锣湾扛把子自动化账号"],
        orderIndicators: [
          {
            label: "佣金率",
            type: 5,
            name: "commissionRateIndicator",
            value: "19%",
            icon: false,
          },
          {
            label: "分成比例",
            type: 6,
            name: "shareRateIndicator",
            value: "90%",
            icon: true,
            action: {
              type: "modal",
              title: "分成比例",
              content: [
                '<div style="margin-bottom: 16px"><span style="font-size: 16px">扣除推广服务费后，你所实际获得的分成比例（你的分成比例90%=商品佣金100%-平台推广服务费比例10%）</span></div>',
                '<div style="margin-bottom: 16px"><span style="font-size: 16px">推广服务费全额返还说明</span></div>',
                '<div style="color: #fe3666; margin-bottom: 16px"><span style="color: #fe3666; font-size: 16px" >•</span> <span style="color: #fe3666; font-size: 16px">2022年9月1日-2023年1月31日期间，平台将对"月末购物体验分>=4分"的达人全额返还推广服务费</span></div>',
                '<div style="color: #fe3666; margin-bottom: 16px"><span style="color: #fe3666; font-size: 16px" >•</span><span style="color: #fe3666; font-size: 16px">返还的推广服务费可在"快手小店PC后台-账户资金-奖金管理"提现</span></div>',
              ],
              btn: {
                type: "jump",
                btnType: "primary",
                title: "查看政策详情",
                url: "https://edu.kwaixiaodian.com/bbs/web/article?id=17963&layoutType=4",
              },
            },
          },
          {
            label: "预估收入",
            type: 7,
            name: "estimatedIncomeIndicator",
            value: "0.00",
            icon: true,
            action: {
              type: "modal",
              title: "预估收入说明",
              content: [
                "预估收入=计佣金额*佣金率*分成比例",
                "若订单包含以下情况，预估收入会做相应扣减:",
                "1.消费者使用了主播红包；",
                "2.订单有服务商/MCN机构角色参与分账。",
              ],
            },
          },
        ],
      },
      track: {},
    },
    CpsOrderGoodsCard_E4zaoPuJTVcyFAVu: {
      instanceId: "CpsOrderGoodsCard_E4zaoPuJTVcyFAVu",
      componentInstanceKey: 1458245002,
      name: "CpsOrderGoodsCard",
      cid: 1620,
      ver: 16,
      style: {
        layout: {
          padding: [16, 0, 16, 0],
          margin: [0, 0, 16, 0],
        },
      },
      engineConfig: {},
      fields: {
        orderId: 2424900045613732,
        settlementBizType: 1,
        orderStatus: {
          value: 6,
          label: "已发货",
          color: "#fe3666",
        },
        imgUrl:
          "https://u1-203.ecukwai.com/bs2/image-kwaishop-product/ITEM_IMAGE-2359894008-1b19a9017b134f8b940ad93562954f77.jpg",
        itemTitle: "订单动态化-二级团专用商品",
        itemPrice: "0.10",
        createTime: 1725542508632,
        cpsOrderType: 2,
        promotionTags: [],
        orderInfos: [
          "店铺名称: 铜锣湾扛把子自动化账号",
          "2024年09月05日 21:22:04 付款",
        ],
        orderIndicators: [
          {
            label: "佣金率",
            type: 5,
            name: "commissionRateIndicator",
            value: "49%",
            icon: false,
          },
          {
            label: "分成比例",
            type: 6,
            name: "shareRateIndicator",
            value: "90%",
            icon: true,
            action: {
              type: "modal",
              title: "分成比例",
              content: [
                '<div style="margin-bottom: 16px"><span style="font-size: 16px">扣除推广服务费后，你所实际获得的分成比例（你的分成比例90%=商品佣金100%-平台推广服务费比例10%）</span></div>',
                '<div style="margin-bottom: 16px"><span style="font-size: 16px">推广服务费全额返还说明</span></div>',
                '<div style="color: #fe3666; margin-bottom: 16px"><span style="color: #fe3666; font-size: 16px" >•</span> <span style="color: #fe3666; font-size: 16px">2022年9月1日-2023年1月31日期间，平台将对"月末购物体验分>=4分"的达人全额返还推广服务费</span></div>',
                '<div style="color: #fe3666; margin-bottom: 16px"><span style="color: #fe3666; font-size: 16px" >•</span><span style="color: #fe3666; font-size: 16px">返还的推广服务费可在"快手小店PC后台-账户资金-奖金管理"提现</span></div>',
              ],
              btn: {
                type: "jump",
                btnType: "primary",
                title: "查看政策详情",
                url: "https://edu.kwaixiaodian.com/bbs/web/article?id=17963&layoutType=4",
              },
            },
          },
          {
            label: "预估收入",
            type: 7,
            name: "estimatedIncomeIndicator",
            value: "0.04",
            icon: true,
            action: {
              type: "modal",
              title: "预估收入说明",
              content: [
                "预估收入=计佣金额*佣金率*分成比例",
                "若订单包含以下情况，预估收入会做相应扣减:",
                "1.消费者使用了主播红包；",
                "2.订单有服务商/MCN机构角色参与分账。",
              ],
            },
          },
        ],
      },
      track: {},
    },
    common_order_list: {
      instanceId: "common_order_list",
      componentInstanceKey: 1452245004,
      name: "cpsCommonGoodsList",
      cid: 1022,
      ver: 11,
      style: {
        layout: {
          padding: [0, 0, 0, 0],
          margin: [0, 0, 0, 0],
        },
      },
      engineConfig: {},
      fields: {},
      strategy: "overwrite",
      track: {},
    },
    CpsOrderGoodsCard_yl2lBaoh8DsyBhII: {
      instanceId: "CpsOrderGoodsCard_yl2lBaoh8DsyBhII",
      componentInstanceKey: 1458245002,
      name: "CpsOrderGoodsCard",
      cid: 1620,
      ver: 16,
      style: {
        layout: {
          padding: [16, 0, 16, 0],
          margin: [0, 0, 16, 0],
        },
      },
      engineConfig: {},
      fields: {
        orderId: 2423600121354732,
        settlementBizType: 1,
        orderStatus: {
          value: 5,
          label: "已失效",
          color: "#c6c6c6",
        },
        imgUrl:
          "https://u1-203.ecukwai.com/bs2/image-kwaishop-product/ITEM_IMAGE-2359894008-1b19a9017b134f8b940ad93562954f77.jpg",
        itemTitle: "达人素材-平台定价托管",
        itemPrice: "0.50",
        createTime: 1724381417669,
        cpsOrderType: 7,
        promotionTags: [
          {
            value: 7,
            label: "快手商城推广",
            action: {
              type: "jump",
              target: "_blank",
              url: "https://docs.qingque.cn/d/home/eZQCP0zCpxFQaOBZIqRQVWwXr?identityId=1oE1lmldGhH",
            },
          },
        ],
        orderInfos: [
          "达人素材在商城场域内展示推广",
          "店铺名称: 铜锣湾扛把子自动化账号",
        ],
        orderIndicators: [
          {
            label: "佣金率",
            type: 5,
            name: "commissionRateIndicator",
            value: "75%",
            icon: false,
          },
          {
            label: "分成比例",
            type: 6,
            name: "shareRateIndicator",
            value: "90%",
            icon: true,
            action: {
              type: "modal",
              title: "分成比例",
              content: ["该订单为快手商城场域内成交，分佣规则可"],
              aLink: {
                title: "查看详情",
                url: "https://docs.qingque.cn/d/home/eZQCP0zCpxFQaOBZIqRQVWwXr?identityId=1rdoxqnN9Od",
              },
            },
          },
          {
            label: "预估收入",
            type: 7,
            name: "estimatedIncomeIndicator",
            value: "0.00",
            icon: true,
            action: {
              type: "modal",
              title: "预估收入说明",
              content: [
                "预估收入=计佣金额*佣金率*分成比例",
                "若订单包含以下情况，预估收入会做相应扣减:",
                "1.消费者使用了主播红包；",
                "2.订单有服务商角色参与分账。",
              ],
            },
          },
        ],
      },
      track: {},
    },
    CpsOrderGoodsCard_ZxIRa5u8hEcPcOz0: {
      instanceId: "CpsOrderGoodsCard_ZxIRa5u8hEcPcOz0",
      componentInstanceKey: 1458245002,
      name: "CpsOrderGoodsCard",
      cid: 1620,
      ver: 16,
      style: {
        layout: {
          padding: [16, 0, 16, 0],
          margin: [0, 0, 16, 0],
        },
      },
      engineConfig: {},
      fields: {
        orderId: 2423600127602732,
        settlementBizType: 1,
        orderStatus: {
          value: 5,
          label: "已失效",
          color: "#c6c6c6",
        },
        imgUrl:
          "https://u1-203.ecukwai.com/bs2/image-kwaishop-product/ITEM_IMAGE-2359894008-1b19a9017b134f8b940ad93562954f77.jpg",
        itemTitle: "开放平台接口优化-团长",
        itemPrice: "0.30",
        createTime: 1724398245270,
        cpsOrderType: 2,
        promotionTags: [],
        orderInfos: ["店铺名称: 铜锣湾扛把子自动化账号"],
        orderIndicators: [
          {
            label: "佣金率",
            type: 5,
            name: "commissionRateIndicator",
            value: "35%",
            icon: false,
          },
          {
            label: "分成比例",
            type: 6,
            name: "shareRateIndicator",
            value: "90%",
            icon: true,
            action: {
              type: "modal",
              title: "分成比例",
              content: [
                '<div style="margin-bottom: 16px"><span style="font-size: 16px">扣除推广服务费后，你所实际获得的分成比例（你的分成比例90%=商品佣金100%-平台推广服务费比例10%）</span></div>',
                '<div style="margin-bottom: 16px"><span style="font-size: 16px">推广服务费全额返还说明</span></div>',
                '<div style="color: #fe3666; margin-bottom: 16px"><span style="color: #fe3666; font-size: 16px" >•</span> <span style="color: #fe3666; font-size: 16px">2022年9月1日-2023年1月31日期间，平台将对"月末购物体验分>=4分"的达人全额返还推广服务费</span></div>',
                '<div style="color: #fe3666; margin-bottom: 16px"><span style="color: #fe3666; font-size: 16px" >•</span><span style="color: #fe3666; font-size: 16px">返还的推广服务费可在"快手小店PC后台-账户资金-奖金管理"提现</span></div>',
              ],
              btn: {
                type: "jump",
                btnType: "primary",
                title: "查看政策详情",
                url: "https://edu.kwaixiaodian.com/bbs/web/article?id=17963&layoutType=4",
              },
            },
          },
          {
            label: "预估收入",
            type: 7,
            name: "estimatedIncomeIndicator",
            value: "0.00",
            icon: true,
            action: {
              type: "modal",
              title: "预估收入说明",
              content: [
                "预估收入=计佣金额*佣金率*分成比例",
                "若订单包含以下情况，预估收入会做相应扣减:",
                "1.消费者使用了主播红包；",
                "2.订单有服务商/MCN机构角色参与分账。",
              ],
            },
          },
        ],
      },
      track: {},
    },
    CpsOrderGoodsCard_5Iy03sNdGFFgtA9H: {
      instanceId: "CpsOrderGoodsCard_5Iy03sNdGFFgtA9H",
      componentInstanceKey: 1458245002,
      name: "CpsOrderGoodsCard",
      cid: 1620,
      ver: 16,
      style: {
        layout: {
          padding: [16, 0, 16, 0],
          margin: [0, 0, 16, 0],
        },
      },
      engineConfig: {},
      fields: {
        orderId: 2423900004350093,
        settlementBizType: 1,
        orderStatus: {
          value: 5,
          label: "已失效",
          color: "#c6c6c6",
        },
        imgUrl:
          "https://u1-203.ecukwai.com/bs2/image-kwaishop-product/ITEM_IMAGE-2428997147-f13cc24c02344d7d88e6fa8a913bec1b.jpg",
        itemTitle: "团长托管回归",
        itemPrice: "30.00",
        createTime: 1724673871558,
        cpsOrderType: 2,
        promotionTags: [],
        orderInfos: ["店铺名称: 多乐乐乐乐改"],
        orderIndicators: [
          {
            label: "佣金率",
            type: 5,
            name: "commissionRateIndicator",
            value: "10%",
            icon: false,
          },
          {
            label: "分成比例",
            type: 6,
            name: "shareRateIndicator",
            value: "90%",
            icon: true,
            action: {
              type: "modal",
              title: "分成比例",
              content: [
                '<div style="margin-bottom: 16px"><span style="font-size: 16px">扣除推广服务费后，你所实际获得的分成比例（你的分成比例90%=商品佣金100%-平台推广服务费比例10%）</span></div>',
                '<div style="margin-bottom: 16px"><span style="font-size: 16px">推广服务费全额返还说明</span></div>',
                '<div style="color: #fe3666; margin-bottom: 16px"><span style="color: #fe3666; font-size: 16px" >•</span> <span style="color: #fe3666; font-size: 16px">2022年9月1日-2023年1月31日期间，平台将对"月末购物体验分>=4分"的达人全额返还推广服务费</span></div>',
                '<div style="color: #fe3666; margin-bottom: 16px"><span style="color: #fe3666; font-size: 16px" >•</span><span style="color: #fe3666; font-size: 16px">返还的推广服务费可在"快手小店PC后台-账户资金-奖金管理"提现</span></div>',
              ],
              btn: {
                type: "jump",
                btnType: "primary",
                title: "查看政策详情",
                url: "https://edu.kwaixiaodian.com/bbs/web/article?id=17963&layoutType=4",
              },
            },
          },
          {
            label: "预估收入",
            type: 7,
            name: "estimatedIncomeIndicator",
            value: "0.00",
            icon: true,
            action: {
              type: "modal",
              title: "预估收入说明",
              content: [
                "预估收入=计佣金额*佣金率*分成比例",
                "若订单包含以下情况，预估收入会做相应扣减:",
                "1.消费者使用了主播红包；",
                "2.订单有服务商/MCN机构角色参与分账。",
              ],
            },
          },
        ],
      },
      track: {},
    },
    CpsOrderGoodsCard_n3Iki7EPAVXDvFy2: {
      instanceId: "CpsOrderGoodsCard_n3Iki7EPAVXDvFy2",
      componentInstanceKey: 1458245002,
      name: "CpsOrderGoodsCard",
      cid: 1620,
      ver: 16,
      style: {
        layout: {
          padding: [16, 0, 16, 0],
          margin: [0, 0, 16, 0],
        },
      },
      engineConfig: {},
      fields: {
        orderId: 2423500124512732,
        settlementBizType: 1,
        orderStatus: {
          value: 5,
          label: "已失效",
          color: "#c6c6c6",
        },
        imgUrl:
          "https://u1-203.ecukwai.com/bs2/image-kwaishop-product/ITEM_IMAGE-2359894008-1b19a9017b134f8b940ad93562954f77.jpg",
        itemTitle: "达人素材-白名单专用",
        itemPrice: "0.30",
        createTime: 1724319215073,
        cpsOrderType: 2,
        promotionTags: [],
        orderInfos: ["店铺名称: 铜锣湾扛把子自动化账号"],
        orderIndicators: [
          {
            label: "佣金率",
            type: 5,
            name: "commissionRateIndicator",
            value: "19%",
            icon: false,
          },
          {
            label: "分成比例",
            type: 6,
            name: "shareRateIndicator",
            value: "90%",
            icon: true,
            action: {
              type: "modal",
              title: "分成比例",
              content: [
                '<div style="margin-bottom: 16px"><span style="font-size: 16px">扣除推广服务费后，你所实际获得的分成比例（你的分成比例90%=商品佣金100%-平台推广服务费比例10%）</span></div>',
                '<div style="margin-bottom: 16px"><span style="font-size: 16px">推广服务费全额返还说明</span></div>',
                '<div style="color: #fe3666; margin-bottom: 16px"><span style="color: #fe3666; font-size: 16px" >•</span> <span style="color: #fe3666; font-size: 16px">2022年9月1日-2023年1月31日期间，平台将对"月末购物体验分>=4分"的达人全额返还推广服务费</span></div>',
                '<div style="color: #fe3666; margin-bottom: 16px"><span style="color: #fe3666; font-size: 16px" >•</span><span style="color: #fe3666; font-size: 16px">返还的推广服务费可在"快手小店PC后台-账户资金-奖金管理"提现</span></div>',
              ],
              btn: {
                type: "jump",
                btnType: "primary",
                title: "查看政策详情",
                url: "https://edu.kwaixiaodian.com/bbs/web/article?id=17963&layoutType=4",
              },
            },
          },
          {
            label: "预估收入",
            type: 7,
            name: "estimatedIncomeIndicator",
            value: "0.00",
            icon: true,
            action: {
              type: "modal",
              title: "预估收入说明",
              content: [
                "预估收入=计佣金额*佣金率*分成比例",
                "若订单包含以下情况，预估收入会做相应扣减:",
                "1.消费者使用了主播红包；",
                "2.订单有服务商/MCN机构角色参与分账。",
              ],
            },
          },
        ],
      },
      track: {},
    },
    CpsOrderGoodsCard_VDVAMRWGbkjbhUUD: {
      instanceId: "CpsOrderGoodsCard_VDVAMRWGbkjbhUUD",
      componentInstanceKey: 1458245002,
      name: "CpsOrderGoodsCard",
      cid: 1620,
      ver: 16,
      style: {
        layout: {
          padding: [16, 0, 16, 0],
          margin: [0, 0, 16, 0],
        },
      },
      engineConfig: {},
      fields: {
        orderId: 2425000044302732,
        settlementBizType: 1,
        orderStatus: {
          value: 6,
          label: "已发货",
          color: "#fe3666",
        },
        imgUrl:
          "https://u1-203.ecukwai.com/bs2/image-kwaishop-product/ITEM_IMAGE-2359894008-1b19a9017b134f8b940ad93562954f77.jpg",
        itemTitle: "订单动态化-普通招商商品",
        itemPrice: "0.10",
        createTime: 1725588708074,
        cpsOrderType: 2,
        promotionTags: [],
        orderInfos: [
          "店铺名称: 铜锣湾扛把子自动化账号",
          "2024年09月06日 10:11:55 付款",
        ],
        orderIndicators: [
          {
            label: "佣金率",
            type: 5,
            name: "commissionRateIndicator",
            value: "48%",
            icon: false,
          },
          {
            label: "分成比例",
            type: 6,
            name: "shareRateIndicator",
            value: "90%",
            icon: true,
            action: {
              type: "modal",
              title: "分成比例",
              content: [
                '<div style="margin-bottom: 16px"><span style="font-size: 16px">扣除推广服务费后，你所实际获得的分成比例（你的分成比例90%=商品佣金100%-平台推广服务费比例10%）</span></div>',
                '<div style="margin-bottom: 16px"><span style="font-size: 16px">推广服务费全额返还说明</span></div>',
                '<div style="color: #fe3666; margin-bottom: 16px"><span style="color: #fe3666; font-size: 16px" >•</span> <span style="color: #fe3666; font-size: 16px">2022年9月1日-2023年1月31日期间，平台将对"月末购物体验分>=4分"的达人全额返还推广服务费</span></div>',
                '<div style="color: #fe3666; margin-bottom: 16px"><span style="color: #fe3666; font-size: 16px" >•</span><span style="color: #fe3666; font-size: 16px">返还的推广服务费可在"快手小店PC后台-账户资金-奖金管理"提现</span></div>',
              ],
              btn: {
                type: "jump",
                btnType: "primary",
                title: "查看政策详情",
                url: "https://edu.kwaixiaodian.com/bbs/web/article?id=17963&layoutType=4",
              },
            },
          },
          {
            label: "预估收入",
            type: 7,
            name: "estimatedIncomeIndicator",
            value: "0.04",
            icon: true,
            action: {
              type: "modal",
              title: "预估收入说明",
              content: [
                "预估收入=计佣金额*佣金率*分成比例",
                "若订单包含以下情况，预估收入会做相应扣减:",
                "1.消费者使用了主播红包；",
                "2.订单有服务商/MCN机构角色参与分账。",
              ],
            },
          },
        ],
      },
      track: {},
    },
    common_order_tab_list: {
      instanceId: "common_order_tab_list",
      componentInstanceKey: 14612450094388476837,
      name: "CommonTabsList",
      cid: 1622,
      ver: 8,
      style: {
        layout: {
          padding: [0, 0, 0, 0],
          margin: [0, 0, 0, 0],
        },
      },
      engineConfig: {},
      fields: {
        title: "CommonTabsList title remote",
        tabsPromotionList: [
          {
            value: 1,
            label: "普通推广",
          },
          {
            value: 2,
            label: "站外推广",
          },
          {
            value: 3,
            label: "授权推广",
          },
          {
            value: 4,
            label: "二创授权推广",
          },
        ],
        tabsPromotionDefaultValue: 2,
      },
      track: {},
    },
    CpsOrderGoodsCard_AsTrglhQLExryCH2: {
      instanceId: "CpsOrderGoodsCard_AsTrglhQLExryCH2",
      componentInstanceKey: 1458245002,
      name: "CpsOrderGoodsCard",
      cid: 1620,
      ver: 16,
      style: {
        layout: {
          padding: [16, 0, 16, 0],
          margin: [0, 0, 16, 0],
        },
      },
      engineConfig: {},
      fields: {
        orderId: 2424800096911732,
        settlementBizType: 1,
        orderStatus: {
          value: 5,
          label: "已失效",
          color: "#c6c6c6",
        },
        imgUrl:
          "https://u1-203.ecukwai.com/bs2/image-kwaishop-product/ITEM_IMAGE-49735288-b80842ad3046498bbad2a94118e4a1a0.jpg",
        itemTitle: "测试品牌创建24-08-5-selectionid优化",
        itemPrice: "3456.23",
        createTime: 1725451943421,
        cpsOrderType: 2,
        promotionTags: [],
        orderInfos: ["店铺名称: 快手优选"],
        orderIndicators: [
          {
            label: "佣金率",
            type: 5,
            name: "commissionRateIndicator",
            value: "17%",
            icon: false,
          },
          {
            label: "分成比例",
            type: 6,
            name: "shareRateIndicator",
            value: "90%",
            icon: true,
            action: {
              type: "modal",
              title: "分成比例",
              content: [
                '<div style="margin-bottom: 16px"><span style="font-size: 16px">扣除推广服务费后，你所实际获得的分成比例（你的分成比例90%=商品佣金100%-平台推广服务费比例10%）</span></div>',
                '<div style="margin-bottom: 16px"><span style="font-size: 16px">推广服务费全额返还说明</span></div>',
                '<div style="color: #fe3666; margin-bottom: 16px"><span style="color: #fe3666; font-size: 16px" >•</span> <span style="color: #fe3666; font-size: 16px">2022年9月1日-2023年1月31日期间，平台将对"月末购物体验分>=4分"的达人全额返还推广服务费</span></div>',
                '<div style="color: #fe3666; margin-bottom: 16px"><span style="color: #fe3666; font-size: 16px" >•</span><span style="color: #fe3666; font-size: 16px">返还的推广服务费可在"快手小店PC后台-账户资金-奖金管理"提现</span></div>',
              ],
              btn: {
                type: "jump",
                btnType: "primary",
                title: "查看政策详情",
                url: "https://edu.kwaixiaodian.com/bbs/web/article?id=17963&layoutType=4",
              },
            },
          },
          {
            label: "预估收入",
            type: 7,
            name: "estimatedIncomeIndicator",
            value: "0.00",
            icon: true,
            action: {
              type: "modal",
              title: "预估收入说明",
              content: [
                "预估收入=计佣金额*佣金率*分成比例",
                "若订单包含以下情况，预估收入会做相应扣减:",
                "1.消费者使用了主播红包；",
                "2.订单有服务商/MCN机构角色参与分账。",
              ],
            },
          },
        ],
      },
      track: {},
    },
    CpsOrderGoodsCard_tfiRwiTgOjZVXjLk: {
      instanceId: "CpsOrderGoodsCard_tfiRwiTgOjZVXjLk",
      componentInstanceKey: 1458245002,
      name: "CpsOrderGoodsCard",
      cid: 1620,
      ver: 16,
      style: {
        layout: {
          padding: [16, 0, 16, 0],
          margin: [0, 0, 16, 0],
        },
      },
      engineConfig: {},
      fields: {
        orderId: 2424900088729732,
        settlementBizType: 4,
        orderStatus: {
          value: 6,
          label: "已发货",
          color: "#fe3666",
        },
        imgUrl:
          "https://u1-203.ecukwai.com/bs2/image-kwaishop-product/ITEM_IMAGE-2359894008-1b19a9017b134f8b940ad93562954f77.jpg",
        itemTitle: "订单动态化-专属招商商品",
        itemPrice: "0.10",
        createTime: 1725543052619,
        cpsOrderType: 6,
        orderTags: [
          {
            value: 100,
            label: "快手聚力计划",
            action: {
              type: "modal",
              title: "快手聚力计划",
              content: ["该类型订单须您向平台开具发票后方可提取剩余款项"],
              aLink: {
                title: "查看详情",
                url: "https://ppg.viviv.com/doodle/CtEyGOBA.html?hyId=jimu_CtEyGOBA&layoutType=4",
              },
            },
          },
        ],
        promotionTags: [
          {
            value: 6,
            label: "内容授权推广",
            action: {
              type: "jump",
              target: "_blank",
              url: "https://docs.qingque.cn/d/home/eZQDoBhHM_gmtyIm7hwyVqJK8?identityId=1oEFmSPaDP2",
            },
          },
        ],
        orderInfos: [
          "店铺名称: 铜锣湾扛把子自动化账号",
          "2024年09月05日 21:31:02 付款",
        ],
        orderIndicators: [
          {
            label: "佣金率",
            type: 12,
            name: "commissionRateActionIndicator",
            value: "8.8%",
            icon: true,
            action: {
              type: "modal",
              title: "佣金率说明",
              content: [
                "合作计划佣金率 44.0%，授权合作分成比例 20.0%，佣金比例 = 44.0%*20.0%",
              ],
            },
          },
          {
            label: "分成比例",
            type: 6,
            name: "shareRateIndicator",
            value: "90%",
            icon: true,
            action: {
              type: "modal",
              title: "分成比例",
              content: [
                '<div style="margin-bottom: 16px"><span style="font-size: 16px">扣除推广服务费后，你所实际获得的分成比例（你的分成比例90%=商品佣金100%-平台推广服务费比例10%）</span></div>',
                '<div style="margin-bottom: 16px"><span style="font-size: 16px">推广服务费全额返还说明</span></div>',
                '<div style="color: #fe3666; margin-bottom: 16px"><span style="color: #fe3666; font-size: 16px" >•</span> <span style="color: #fe3666; font-size: 16px">2022年9月1日-2023年1月31日期间，平台将对"月末购物体验分>=4分"的达人全额返还推广服务费</span></div>',
                '<div style="color: #fe3666; margin-bottom: 16px"><span style="color: #fe3666; font-size: 16px" >•</span><span style="color: #fe3666; font-size: 16px">返还的推广服务费可在"快手小店PC后台-账户资金-奖金管理"提现</span></div>',
              ],
              btn: {
                type: "jump",
                btnType: "primary",
                title: "查看政策详情",
                url: "https://edu.kwaixiaodian.com/bbs/web/article?id=17963&layoutType=4",
              },
            },
          },
          {
            label: "预估收入",
            type: 7,
            name: "estimatedIncomeIndicator",
            value: "0.00",
            icon: true,
            action: {
              type: "modal",
              title: "预估收入说明",
              content: [],
            },
          },
        ],
      },
      track: {},
    },
    KUAISHOU_ERA_ROOT: {
      instanceId: "KUAISHOU_ERA_ROOT",
      componentInstanceKey: 1001,
      name: "infinity_root_node",
      cid: 0,
      ver: 1,
      style: {},
      engineConfig: {},
      fields: {},
      track: {},
    },
    CpsOrderGoodsCard_vuJhh0bNKHrg69wZ: {
      instanceId: "CpsOrderGoodsCard_vuJhh0bNKHrg69wZ",
      componentInstanceKey: 1458245002,
      name: "CpsOrderGoodsCard",
      cid: 1620,
      ver: 16,
      style: {
        layout: {
          padding: [16, 0, 16, 0],
          margin: [0, 0, 16, 0],
        },
      },
      engineConfig: {},
      fields: {
        orderId: 2423500087814093,
        settlementBizType: 1,
        orderStatus: {
          value: 5,
          label: "已失效",
          color: "#c6c6c6",
        },
        imgUrl:
          "https://u1-203.ecukwai.com/bs2/image-kwaishop-product/item-11318492-d3b05bd76f1a44a6a5d966eb5a3eb9be.jpg",
        itemTitle: "喵小姐「自动化测试」-团长托管，勿动不发货",
        itemPrice: "60.00",
        createTime: 1724333658474,
        cpsOrderType: 2,
        promotionTags: [],
        orderInfos: ["店铺名称: dstest059"],
        orderIndicators: [
          {
            label: "佣金率",
            type: 5,
            name: "commissionRateIndicator",
            value: "11%",
            icon: false,
          },
          {
            label: "分成比例",
            type: 6,
            name: "shareRateIndicator",
            value: "90%",
            icon: true,
            action: {
              type: "modal",
              title: "分成比例",
              content: [
                '<div style="margin-bottom: 16px"><span style="font-size: 16px">扣除推广服务费后，你所实际获得的分成比例（你的分成比例90%=商品佣金100%-平台推广服务费比例10%）</span></div>',
                '<div style="margin-bottom: 16px"><span style="font-size: 16px">推广服务费全额返还说明</span></div>',
                '<div style="color: #fe3666; margin-bottom: 16px"><span style="color: #fe3666; font-size: 16px" >•</span> <span style="color: #fe3666; font-size: 16px">2022年9月1日-2023年1月31日期间，平台将对"月末购物体验分>=4分"的达人全额返还推广服务费</span></div>',
                '<div style="color: #fe3666; margin-bottom: 16px"><span style="color: #fe3666; font-size: 16px" >•</span><span style="color: #fe3666; font-size: 16px">返还的推广服务费可在"快手小店PC后台-账户资金-奖金管理"提现</span></div>',
              ],
              btn: {
                type: "jump",
                btnType: "primary",
                title: "查看政策详情",
                url: "https://edu.kwaixiaodian.com/bbs/web/article?id=17963&layoutType=4",
              },
            },
          },
          {
            label: "预估收入",
            type: 7,
            name: "estimatedIncomeIndicator",
            value: "0.00",
            icon: true,
            action: {
              type: "modal",
              title: "预估收入说明",
              content: [
                "预估收入=计佣金额*佣金率*分成比例",
                "若订单包含以下情况，预估收入会做相应扣减:",
                "1.消费者使用了主播红包；",
                "2.订单有服务商/MCN机构角色参与分账。",
              ],
            },
          },
        ],
      },
      track: {},
    },
    CpsOrderGoodsCard_sCFK9L3kGq50LPqb: {
      instanceId: "CpsOrderGoodsCard_sCFK9L3kGq50LPqb",
      componentInstanceKey: 1458245002,
      name: "CpsOrderGoodsCard",
      cid: 1620,
      ver: 16,
      style: {
        layout: {
          padding: [16, 0, 16, 0],
          margin: [0, 0, 16, 0],
        },
      },
      engineConfig: {},
      fields: {
        orderId: 2423900125201732,
        settlementBizType: 1,
        orderStatus: {
          value: 4,
          label: "已结算",
          color: "#36cfa2",
        },
        imgUrl:
          "https://u1-203.ecukwai.com/bs2/image-kwaishop-product/ITEM_IMAGE-2359894008-1b19a9017b134f8b940ad93562954f77.jpg",
        itemTitle: "达人素材-签约专用",
        itemPrice: "0.20",
        createTime: 1724642637550,
        cpsOrderType: 7,
        promotionTags: [
          {
            value: 7,
            label: "快手商城推广",
            action: {
              type: "jump",
              target: "_blank",
              url: "https://docs.qingque.cn/d/home/eZQCP0zCpxFQaOBZIqRQVWwXr?identityId=1oE1lmldGhH",
            },
          },
        ],
        orderInfos: [
          "达人素材在商城场域内展示推广",
          "店铺名称: 铜锣湾扛把子自动化账号",
          "2024年08月26日 11:24:06 付款",
          "2024年09月04日 12:48:11 结算",
        ],
        orderIndicators: [
          {
            label: "佣金率",
            type: 5,
            name: "commissionRateIndicator",
            value: "54%",
            icon: false,
          },
          {
            label: "分成比例",
            type: 6,
            name: "shareRateIndicator",
            value: "90%",
            icon: true,
            action: {
              type: "modal",
              title: "分成比例",
              content: ["该订单为快手商城场域内成交，分佣规则可"],
              aLink: {
                title: "查看详情",
                url: "https://docs.qingque.cn/d/home/eZQCP0zCpxFQaOBZIqRQVWwXr?identityId=1rdoxqnN9Od",
              },
            },
          },
          {
            label: "预估收入",
            type: 7,
            name: "estimatedIncomeIndicator",
            value: "0.09",
            icon: true,
            action: {
              type: "modal",
              title: "预估收入说明",
              content: [
                "预估收入=计佣金额*佣金率*分成比例",
                "若订单包含以下情况，预估收入会做相应扣减:",
                "1.消费者使用了主播红包；",
                "2.订单有服务商角色参与分账。",
              ],
            },
          },
        ],
      },
      track: {},
    },
    CpsOrderGoodsCard_XD7BruGO525FGJxj: {
      instanceId: "CpsOrderGoodsCard_XD7BruGO525FGJxj",
      componentInstanceKey: 1458245002,
      name: "CpsOrderGoodsCard",
      cid: 1620,
      ver: 16,
      style: {
        layout: {
          padding: [16, 0, 16, 0],
          margin: [0, 0, 16, 0],
        },
      },
      engineConfig: {},
      fields: {
        orderId: 2423600123662732,
        settlementBizType: 1,
        orderStatus: {
          value: 6,
          label: "已发货",
          color: "#fe3666",
        },
        imgUrl:
          "https://u1-203.ecukwai.com/bs2/image-kwaishop-product/ITEM_IMAGE-2359894008-1b19a9017b134f8b940ad93562954f77.jpg",
        itemTitle: "达人素材-签约专用",
        itemPrice: "0.20",
        createTime: 1724381473751,
        cpsOrderType: 7,
        promotionTags: [
          {
            value: 7,
            label: "快手商城推广",
            action: {
              type: "jump",
              target: "_blank",
              url: "https://docs.qingque.cn/d/home/eZQCP0zCpxFQaOBZIqRQVWwXr?identityId=1oE1lmldGhH",
            },
          },
        ],
        orderInfos: [
          "达人素材在商城场域内展示推广",
          "店铺名称: 铜锣湾扛把子自动化账号",
          "2024年08月23日 10:51:44 付款",
        ],
        orderIndicators: [
          {
            label: "佣金率",
            type: 5,
            name: "commissionRateIndicator",
            value: "54%",
            icon: false,
          },
          {
            label: "分成比例",
            type: 6,
            name: "shareRateIndicator",
            value: "90%",
            icon: true,
            action: {
              type: "modal",
              title: "分成比例",
              content: ["该订单为快手商城场域内成交，分佣规则可"],
              aLink: {
                title: "查看详情",
                url: "https://docs.qingque.cn/d/home/eZQCP0zCpxFQaOBZIqRQVWwXr?identityId=1rdoxqnN9Od",
              },
            },
          },
          {
            label: "预估收入",
            type: 7,
            name: "estimatedIncomeIndicator",
            value: "0.09",
            icon: true,
            action: {
              type: "modal",
              title: "预估收入说明",
              content: [
                "预估收入=计佣金额*佣金率*分成比例",
                "若订单包含以下情况，预估收入会做相应扣减:",
                "1.消费者使用了主播红包；",
                "2.订单有服务商角色参与分账。",
              ],
            },
          },
        ],
      },
      track: {},
    },
    cps_order_status_list: {
      instanceId: "cps_order_status_list",
      componentInstanceKey: 1583245002,
      name: "CpsOrderStatus",
      cid: 1821,
      ver: 1,
      style: {
        layout: {
          padding: [0, 0, 0, 0],
          margin: [0, 0, 0, 0],
        },
      },
      engineConfig: {},
      fields: {
        tabsOrderStatusList: [
          {
            value: 1,
            label: "全部",
          },
          {
            value: 2,
            label: "已付款",
          },
          {
            value: 3,
            label: "已收货",
          },
          {
            value: 4,
            label: "已结算",
          },
          {
            value: 5,
            label: "已失效",
          },
        ],
        tabsOrderStatusDefaultValue: 1,
      },
      track: {},
    },
    CpsOrderGoodsCard_4HL5PaB7XWDwK5GO: {
      instanceId: "CpsOrderGoodsCard_4HL5PaB7XWDwK5GO",
      componentInstanceKey: 1458245002,
      name: "CpsOrderGoodsCard",
      cid: 1620,
      ver: 16,
      style: {
        layout: {
          padding: [16, 0, 16, 0],
          margin: [0, 0, 16, 0],
        },
      },
      engineConfig: {},
      fields: {
        orderId: 2423600127607732,
        settlementBizType: 1,
        orderStatus: {
          value: 5,
          label: "已失效",
          color: "#c6c6c6",
        },
        imgUrl:
          "https://u1-203.ecukwai.com/bs2/image-kwaishop-product/ITEM_IMAGE-2359894008-1b19a9017b134f8b940ad93562954f77.jpg",
        itemTitle: "开放平台接口优化-团长",
        itemPrice: "0.30",
        createTime: 1724398420232,
        cpsOrderType: 2,
        promotionTags: [],
        orderInfos: ["店铺名称: 铜锣湾扛把子自动化账号"],
        orderIndicators: [
          {
            label: "佣金率",
            type: 5,
            name: "commissionRateIndicator",
            value: "35%",
            icon: false,
          },
          {
            label: "分成比例",
            type: 6,
            name: "shareRateIndicator",
            value: "90%",
            icon: true,
            action: {
              type: "modal",
              title: "分成比例",
              content: [
                '<div style="margin-bottom: 16px"><span style="font-size: 16px">扣除推广服务费后，你所实际获得的分成比例（你的分成比例90%=商品佣金100%-平台推广服务费比例10%）</span></div>',
                '<div style="margin-bottom: 16px"><span style="font-size: 16px">推广服务费全额返还说明</span></div>',
                '<div style="color: #fe3666; margin-bottom: 16px"><span style="color: #fe3666; font-size: 16px" >•</span> <span style="color: #fe3666; font-size: 16px">2022年9月1日-2023年1月31日期间，平台将对"月末购物体验分>=4分"的达人全额返还推广服务费</span></div>',
                '<div style="color: #fe3666; margin-bottom: 16px"><span style="color: #fe3666; font-size: 16px" >•</span><span style="color: #fe3666; font-size: 16px">返还的推广服务费可在"快手小店PC后台-账户资金-奖金管理"提现</span></div>',
              ],
              btn: {
                type: "jump",
                btnType: "primary",
                title: "查看政策详情",
                url: "https://edu.kwaixiaodian.com/bbs/web/article?id=17963&layoutType=4",
              },
            },
          },
          {
            label: "预估收入",
            type: 7,
            name: "estimatedIncomeIndicator",
            value: "0.00",
            icon: true,
            action: {
              type: "modal",
              title: "预估收入说明",
              content: [
                "预估收入=计佣金额*佣金率*分成比例",
                "若订单包含以下情况，预估收入会做相应扣减:",
                "1.消费者使用了主播红包；",
                "2.订单有服务商/MCN机构角色参与分账。",
              ],
            },
          },
        ],
      },
      track: {},
    },
    CpsOrderGoodsCard_cbQtitRVGxZBnDJW: {
      instanceId: "CpsOrderGoodsCard_cbQtitRVGxZBnDJW",
      componentInstanceKey: 1458245002,
      name: "CpsOrderGoodsCard",
      cid: 1620,
      ver: 16,
      style: {
        layout: {
          padding: [16, 0, 16, 0],
          margin: [0, 0, 16, 0],
        },
      },
      engineConfig: {},
      fields: {
        orderId: 2423500148662093,
        settlementBizType: 1,
        orderStatus: {
          value: 5,
          label: "已失效",
          color: "#c6c6c6",
        },
        imgUrl:
          "https://u1-203.ecukwai.com/bs2/image-kwaishop-product/item-11318492-d3b05bd76f1a44a6a5d966eb5a3eb9be.jpg",
        itemTitle: "喵小姐「自动化测试」-团长托管，勿动不发货",
        itemPrice: "30.00",
        createTime: 1724335025563,
        cpsOrderType: 2,
        promotionTags: [],
        orderInfos: ["店铺名称: dstest059"],
        orderIndicators: [
          {
            label: "佣金率",
            type: 5,
            name: "commissionRateIndicator",
            value: "11%",
            icon: false,
          },
          {
            label: "分成比例",
            type: 6,
            name: "shareRateIndicator",
            value: "90%",
            icon: true,
            action: {
              type: "modal",
              title: "分成比例",
              content: [
                '<div style="margin-bottom: 16px"><span style="font-size: 16px">扣除推广服务费后，你所实际获得的分成比例（你的分成比例90%=商品佣金100%-平台推广服务费比例10%）</span></div>',
                '<div style="margin-bottom: 16px"><span style="font-size: 16px">推广服务费全额返还说明</span></div>',
                '<div style="color: #fe3666; margin-bottom: 16px"><span style="color: #fe3666; font-size: 16px" >•</span> <span style="color: #fe3666; font-size: 16px">2022年9月1日-2023年1月31日期间，平台将对"月末购物体验分>=4分"的达人全额返还推广服务费</span></div>',
                '<div style="color: #fe3666; margin-bottom: 16px"><span style="color: #fe3666; font-size: 16px" >•</span><span style="color: #fe3666; font-size: 16px">返还的推广服务费可在"快手小店PC后台-账户资金-奖金管理"提现</span></div>',
              ],
              btn: {
                type: "jump",
                btnType: "primary",
                title: "查看政策详情",
                url: "https://edu.kwaixiaodian.com/bbs/web/article?id=17963&layoutType=4",
              },
            },
          },
          {
            label: "预估收入",
            type: 7,
            name: "estimatedIncomeIndicator",
            value: "0.00",
            icon: true,
            action: {
              type: "modal",
              title: "预估收入说明",
              content: [
                "预估收入=计佣金额*佣金率*分成比例",
                "若订单包含以下情况，预估收入会做相应扣减:",
                "1.消费者使用了主播红包；",
                "2.订单有服务商/MCN机构角色参与分账。",
              ],
            },
          },
        ],
      },
      track: {},
    },
    CpsOrderGoodsCard_OgDAIkI0uL9TEXxW: {
      instanceId: "CpsOrderGoodsCard_OgDAIkI0uL9TEXxW",
      componentInstanceKey: 1458245002,
      name: "CpsOrderGoodsCard",
      cid: 1620,
      ver: 16,
      style: {
        layout: {
          padding: [16, 0, 16, 0],
          margin: [0, 0, 16, 0],
        },
      },
      engineConfig: {},
      fields: {
        orderId: 2424900150322732,
        settlementBizType: 1,
        orderStatus: {
          value: 6,
          label: "已发货",
          color: "#fe3666",
        },
        imgUrl:
          "https://u1-203.ecukwai.com/bs2/image-kwaishop-product/ITEM_IMAGE-2359894008-1b19a9017b134f8b940ad93562954f77.jpg",
        itemTitle: "订单动态化-二级团专用商品",
        itemPrice: "0.10",
        createTime: 1725542585134,
        cpsOrderType: 2,
        promotionTags: [],
        orderInfos: [
          "店铺名称: 铜锣湾扛把子自动化账号",
          "2024年09月05日 21:23:11 付款",
        ],
        orderIndicators: [
          {
            label: "佣金率",
            type: 5,
            name: "commissionRateIndicator",
            value: "49%",
            icon: false,
          },
          {
            label: "分成比例",
            type: 6,
            name: "shareRateIndicator",
            value: "90%",
            icon: true,
            action: {
              type: "modal",
              title: "分成比例",
              content: [
                '<div style="margin-bottom: 16px"><span style="font-size: 16px">扣除推广服务费后，你所实际获得的分成比例（你的分成比例90%=商品佣金100%-平台推广服务费比例10%）</span></div>',
                '<div style="margin-bottom: 16px"><span style="font-size: 16px">推广服务费全额返还说明</span></div>',
                '<div style="color: #fe3666; margin-bottom: 16px"><span style="color: #fe3666; font-size: 16px" >•</span> <span style="color: #fe3666; font-size: 16px">2022年9月1日-2023年1月31日期间，平台将对"月末购物体验分>=4分"的达人全额返还推广服务费</span></div>',
                '<div style="color: #fe3666; margin-bottom: 16px"><span style="color: #fe3666; font-size: 16px" >•</span><span style="color: #fe3666; font-size: 16px">返还的推广服务费可在"快手小店PC后台-账户资金-奖金管理"提现</span></div>',
              ],
              btn: {
                type: "jump",
                btnType: "primary",
                title: "查看政策详情",
                url: "https://edu.kwaixiaodian.com/bbs/web/article?id=17963&layoutType=4",
              },
            },
          },
          {
            label: "预估收入",
            type: 7,
            name: "estimatedIncomeIndicator",
            value: "0.04",
            icon: true,
            action: {
              type: "modal",
              title: "预估收入说明",
              content: [
                "预估收入=计佣金额*佣金率*分成比例",
                "若订单包含以下情况，预估收入会做相应扣减:",
                "1.消费者使用了主播红包；",
                "2.订单有服务商/MCN机构角色参与分账。",
              ],
            },
          },
        ],
      },
      track: {},
    },
    CpsOrderGoodsCard_Yvkus8jGUr0RmAvQ: {
      instanceId: "CpsOrderGoodsCard_Yvkus8jGUr0RmAvQ",
      componentInstanceKey: 1458245002,
      name: "CpsOrderGoodsCard",
      cid: 1620,
      ver: 16,
      style: {
        layout: {
          padding: [16, 0, 16, 0],
          margin: [0, 0, 16, 0],
        },
      },
      engineConfig: {},
      fields: {
        orderId: 2423900041653732,
        settlementBizType: 1,
        orderStatus: {
          value: 4,
          label: "已结算",
          color: "#36cfa2",
        },
        imgUrl:
          "https://u1-203.ecukwai.com/bs2/image-kwaishop-product/ITEM_IMAGE-2359894008-1b19a9017b134f8b940ad93562954f77.jpg",
        itemTitle: "达人素材-签约专用",
        itemPrice: "0.20",
        createTime: 1724641835858,
        cpsOrderType: 7,
        promotionTags: [
          {
            value: 7,
            label: "快手商城推广",
            action: {
              type: "jump",
              target: "_blank",
              url: "https://docs.qingque.cn/d/home/eZQCP0zCpxFQaOBZIqRQVWwXr?identityId=1oE1lmldGhH",
            },
          },
        ],
        orderInfos: [
          "达人素材在商城场域内展示推广",
          "店铺名称: 铜锣湾扛把子自动化账号",
          "2024年08月26日 11:10:53 付款",
          "2024年09月05日 13:57:15 结算",
        ],
        orderIndicators: [
          {
            label: "佣金率",
            type: 5,
            name: "commissionRateIndicator",
            value: "54%",
            icon: false,
          },
          {
            label: "分成比例",
            type: 6,
            name: "shareRateIndicator",
            value: "90%",
            icon: true,
            action: {
              type: "modal",
              title: "分成比例",
              content: ["该订单为快手商城场域内成交，分佣规则可"],
              aLink: {
                title: "查看详情",
                url: "https://docs.qingque.cn/d/home/eZQCP0zCpxFQaOBZIqRQVWwXr?identityId=1rdoxqnN9Od",
              },
            },
          },
          {
            label: "预估收入",
            type: 7,
            name: "estimatedIncomeIndicator",
            value: "0.09",
            icon: true,
            action: {
              type: "modal",
              title: "预估收入说明",
              content: [
                "预估收入=计佣金额*佣金率*分成比例",
                "若订单包含以下情况，预估收入会做相应扣减:",
                "1.消费者使用了主播红包；",
                "2.订单有服务商角色参与分账。",
              ],
            },
          },
        ],
      },
      track: {},
    },
    CpsOrderGoodsCard_fej1hEF5cMaH6xsb: {
      instanceId: "CpsOrderGoodsCard_fej1hEF5cMaH6xsb",
      componentInstanceKey: 1458245002,
      name: "CpsOrderGoodsCard",
      cid: 1620,
      ver: 16,
      style: {
        layout: {
          padding: [16, 0, 16, 0],
          margin: [0, 0, 16, 0],
        },
      },
      engineConfig: {},
      fields: {
        orderId: 2423600127601732,
        settlementBizType: 1,
        orderStatus: {
          value: 5,
          label: "已失效",
          color: "#c6c6c6",
        },
        imgUrl:
          "https://u1-203.ecukwai.com/bs2/image-kwaishop-product/ITEM_IMAGE-2359894008-1b19a9017b134f8b940ad93562954f77.jpg",
        itemTitle: "开放平台接口优化-团长",
        itemPrice: "0.60",
        createTime: 1724398231141,
        cpsOrderType: 2,
        promotionTags: [],
        orderInfos: ["店铺名称: 铜锣湾扛把子自动化账号"],
        orderIndicators: [
          {
            label: "佣金率",
            type: 5,
            name: "commissionRateIndicator",
            value: "35%",
            icon: false,
          },
          {
            label: "分成比例",
            type: 6,
            name: "shareRateIndicator",
            value: "90%",
            icon: true,
            action: {
              type: "modal",
              title: "分成比例",
              content: [
                '<div style="margin-bottom: 16px"><span style="font-size: 16px">扣除推广服务费后，你所实际获得的分成比例（你的分成比例90%=商品佣金100%-平台推广服务费比例10%）</span></div>',
                '<div style="margin-bottom: 16px"><span style="font-size: 16px">推广服务费全额返还说明</span></div>',
                '<div style="color: #fe3666; margin-bottom: 16px"><span style="color: #fe3666; font-size: 16px" >•</span> <span style="color: #fe3666; font-size: 16px">2022年9月1日-2023年1月31日期间，平台将对"月末购物体验分>=4分"的达人全额返还推广服务费</span></div>',
                '<div style="color: #fe3666; margin-bottom: 16px"><span style="color: #fe3666; font-size: 16px" >•</span><span style="color: #fe3666; font-size: 16px">返还的推广服务费可在"快手小店PC后台-账户资金-奖金管理"提现</span></div>',
              ],
              btn: {
                type: "jump",
                btnType: "primary",
                title: "查看政策详情",
                url: "https://edu.kwaixiaodian.com/bbs/web/article?id=17963&layoutType=4",
              },
            },
          },
          {
            label: "预估收入",
            type: 7,
            name: "estimatedIncomeIndicator",
            value: "0.00",
            icon: true,
            action: {
              type: "modal",
              title: "预估收入说明",
              content: [
                "预估收入=计佣金额*佣金率*分成比例",
                "若订单包含以下情况，预估收入会做相应扣减:",
                "1.消费者使用了主播红包；",
                "2.订单有服务商/MCN机构角色参与分账。",
              ],
            },
          },
        ],
      },
      track: {},
    },
  },
  hierarchy: {
    root: "KUAISHOU_ERA_ROOT",
    structure: {
      KUAISHOU_ERA_ROOT: [
        "common_order_tab_list",
        "CompA",
        "CompB",
        "CompC",
        "ComponentWithErrorBoundary",
        "common_order_list",
      ],
      common_order_list: [
        "CpsOrderGoodsCard_C4SZPIEnfpnxlVSJ",
        "CpsOrderGoodsCard_VDVAMRWGbkjbhUUD",
        "CpsOrderGoodsCard_tfiRwiTgOjZVXjLk",
        "CpsOrderGoodsCard_OgDAIkI0uL9TEXxW",
        "CpsOrderGoodsCard_E4zaoPuJTVcyFAVu",
        "CpsOrderGoodsCard_fxQbDWQ4ZolYMdRB",
        "CpsOrderGoodsCard_AsTrglhQLExryCH2",
        "CpsOrderGoodsCard_5Iy03sNdGFFgtA9H",
        "CpsOrderGoodsCard_sqyeMdGxs08TUduw",
        "CpsOrderGoodsCard_sCFK9L3kGq50LPqb",
        "CpsOrderGoodsCard_Yvkus8jGUr0RmAvQ",
        "CpsOrderGoodsCard_4HL5PaB7XWDwK5GO",
        "CpsOrderGoodsCard_ZxIRa5u8hEcPcOz0",
        "CpsOrderGoodsCard_fej1hEF5cMaH6xsb",
        "CpsOrderGoodsCard_YRqyjI8k5moBEhoz",
        "CpsOrderGoodsCard_XD7BruGO525FGJxj",
        "CpsOrderGoodsCard_yl2lBaoh8DsyBhII",
        "CpsOrderGoodsCard_cbQtitRVGxZBnDJW",
        "CpsOrderGoodsCard_vuJhh0bNKHrg69wZ",
        "CpsOrderGoodsCard_n3Iki7EPAVXDvFy2",
      ],
    },
  },
  global: {
    protocolVersion: 2,
    commonData: {
      pcursor: "20",
      total: 327,
      promotionOrderRebuildSwitch: false,
    },
    pageName: "CpsOrderPromotionPage",
    pageVersion: 3,
  },
};
